Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KhumaloCraftST10152316.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeRepository _ProductTypeRepo;

        public ProductTypeController(IProductTypeRepository ProductTypeRepo)
        {
            _ProductTypeRepo = ProductTypeRepo;
        }

        public async Task<IActionResult> Index()
        {
            var ProductTypes = await _ProductTypeRepo.GetProductTypes();
            return View(ProductTypes);
        }

        public IActionResult AddProductType()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProductType(ProductTypeDTO ProductType)
        {
            if(!ModelState.IsValid)
            {
                return View(ProductType);
            }
            try
            {
                var ProductTypeToAdd = new ProductType { ProductTypeName = ProductType.ProductTypeName, Id = ProductType.Id };
                await _ProductTypeRepo.AddProductType(ProductTypeToAdd);
                TempData["successMessage"] = "ProductType added successfully";
                return RedirectToAction(nameof(AddProductType));
            }
            catch(Exception ex)
            {
                TempData["errorMessage"] = "ProductType could not added!";
                return View(ProductType);
            }

        }

        public async Task<IActionResult> UpdateProductType(int id)
        {
            var ProductType = await _ProductTypeRepo.GetProductTypeById(id);
            if (ProductType is null)
                throw new InvalidOperationException($"ProductType with id: {id} does not found");
            var ProductTypeToUpdate = new ProductTypeDTO
            {
                Id = ProductType.Id,
                ProductTypeName = ProductType.ProductTypeName
            };
            return View(ProductTypeToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductType(ProductTypeDTO ProductTypeToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(ProductTypeToUpdate);
            }
            try
            {
                var ProductType = new ProductType { ProductTypeName = ProductTypeToUpdate.ProductTypeName, Id = ProductTypeToUpdate.Id };
                await _ProductTypeRepo.UpdateProductType(ProductType);
                TempData["successMessage"] = "ProductType is updated successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "ProductType could not updated!";
                return View(ProductTypeToUpdate);
            }

        }

        public async Task<IActionResult> DeleteProductType(int id)
        {
            var ProductType = await _ProductTypeRepo.GetProductTypeById(id);
            if (ProductType is null)
                throw new InvalidOperationException($"ProductType with id: {id} does not found");
            await _ProductTypeRepo.DeleteProductType(ProductType);
            return RedirectToAction(nameof(Index));

        }

    }
}

Views/ProductType/AddProductType.cshtml
@model ProductTypeDTO
@{
    Layout = "_AdminLayout";
}
@* @Html.ValidationSummary() *@
<div style="width:50%">
<h2> Add ProductType </h2>
<a asp-action="Index" asp-controller="ProductType" class="btn btn-primary">Back</a>
<form asp-action="AddProductType">
   @* <input type="hidden" asp-for="Id" /> *@

   <div class="my-2">
      <label>ProductType</label>
      <input type="text" class="form-control" asp-for="ProductTypeName" />
            <span asp-validation-for="ProductTypeName" class="text-danger"></span>
   </div>

   <div class="my-2">
      <button type="submit" class="btn btn-info">Add</button>
   </div>
</form>
</div>

Views/ProductType/Index.cshtml
@model IEnumerable<ProductType>
@{
    Layout = "_AdminLayout";
}

<h2>ProductTypes</h2>

<a asp-action="AddProductType" asp-controller="ProductType" class="btn btn-primary">Add More</a>

<table class="table table-striped my-2">
    <tr>
        <th>ProductType</th>
        <th>Action</th>
    </tr>

    @foreach(var ProductType in Model)
    {
        <tr>
            <td>@ProductType.ProductTypeName</td>
            <td>
                <a asp-action="UpdateProductType" asp-controller="ProductType" asp-route-id="@ProductType.Id" class="btn btn-success">Edit</a>
                <a asp-action="DeleteProductType" asp-controller="ProductType" asp-route-id="@ProductType.Id" class="btn btn-danger" onclick="return window.confirm('Are you sure?')">Delete</a>
            </td>
        </tr>
    }
</table>

Views/ProductType/UpdateProductType.cshtml
@model ProductTypeDTO
@{
    Layout = "_AdminLayout";
}
@* @Html.ValidationSummary() *@
<div style="width:50%">
<h2> Update ProductType </h2>
<a asp-action="Index" asp-controller="ProductType" class="btn btn-primary">Back</a>
<form asp-action="UpdateProductType">
   <input type="hidden" asp-for="Id" />

   <div class="my-2">
      <label>ProductType</label>
      <input type="text" class="form-control" asp-for="ProductTypeName" />
            <span asp-validation-for="ProductTypeName" class="text-danger"></span>
   </div>

   <div class="my-2">
      <button type="submit" class="btn btn-info">Update</button>
   </div>
</form>
</div>